spring.application.name=PriceManager

# MySQL configuration
spring.datasource.url=jdbc:mysql://localhost:3306/pricemanagerdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=06041925Gx#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
